### ISSUE TITLE
Hang when listing directory with the mountpoint

### ISSUE THREAD

**Issue by mgorny** [pluser/fusebox#3]
Not sure what's really happening here but I've mounted it in `/tmp/test` and upon:

```
cd /tmp/test/tmp
ls
```

it just hangs after:
```
unique: 258, opcode: READDIRPLUS (44), nodeid: 645, insize: 80, pid: 55175
getatter path: /tmp/test, fd: None
```

**Comment by pluser** [comment]
Thank you for the report.
Such an operation cause deadlock.
For example, `ls /tmp/test/tmp` cause access to `/tmp/test`. So another operation cause when processing an operation.
To avoid such a situation, I implement that redirect from `/tmp/test` to source directory `/`.
It will be fixed at https://github.com/pluser/fusebox/commit/c47e97d5bddb84c66ab47148a5ed3afd2dff7109 .
