### ISSUE TITLE
please implement stacked ACLs

### ISSUE THREAD

**Issue by mgorny** [pluser/fusebox#6]
Please implement ACLs based on https://bugs.gentoo.org/729464 with all four commands supported via control pipe.

**Comment by pluser** [comment]
Thank you for your comment / review.
The four commands are addread, addwrite, adddeny, and addpredict, right?
If so, what is addpredict?
In the document/comment, addpredict is explained as below.

> Add one single additional item to the sandbox predict (pretend to allow write) list.

> respective paths are not writable, but no access violation will be issued in the case of a write

I'm reading portage/sandbox code too, but I have not understood the difference between addpredict and addread/addwrite yet.
Should I just discard the writing? Like /dev/null?

**Comment by mgorny** [comment]
Exactly that - you should discard whatever is written into the file and return success.

**Comment by pluser** [comment]
I complete to implement, but there may still be some bugs (but unit test says ok).

**Comment by pluser** [comment]
I need some additional implementation. Fusebox should support fake create(), mkdir(), rmdir(), right?

**Comment by mgorny** [comment]
Not sure, tbh. The primary use for `addpredict` is to mock device nodes.

**Comment by pluser** [comment]
I see.
ok. I checked and fixed few bugs.
It seems good in general.

**Comment by mgorny** [comment]
Cool work, thanks!
